#!/bin/sh

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

DEVICE=solana

mkdir -p ../../../vendor/motorola/$DEVICE/proprietary

adb pull /system/etc/01_Vendor_ti_omx.cfg ../../../vendor/motorola/$DEVICE/proprietary
adb pull /system/lib/egl/libEGL_POWERVR_SGX540_120.so ../../../vendor/motorola/$DEVICE/proprietary
adb pull /system/lib/egl/libGLES_android.so ../../../vendor/motorola/$DEVICE/proprietary
adb pull /system/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so ../../../vendor/motorola/$DEVICE/proprietary
adb pull /system/lib/egl/libGLESv2_POWERVR_SGX540_120.so ../../../vendor/motorola/$DEVICE/proprietary
adb pull /system/lib/egl/libeglinfo.so ../../../vendor/motorola/$DEVICE/proprietary
adb pull /system/lib/egl/libgles1_texture_stream.so ../../../vendor/motorola/$DEVICE/proprietary
adb pull /system/lib/egl/libgles2_texture_stream.so ../../../vendor/motorola/$DEVICE/proprietary
adb pull /system/lib/libEGL.so ../../../vendor/motorola/$DEVICE/proprietary
adb pull /system/lib/libGLESv1_CM.so ../../../vendor/motorola/$DEVICE/proprietary
adb pull /system/lib/libGLESv2.so ../../../vendor/motorola/$DEVICE/proprietary
adb pull /system/lib/libIMGegl.so ../../../vendor/motorola/$DEVICE/proprietary
adb pull /system/lib/libpixelflinger.so ../../../vendor/motorola/$DEVICE/proprietary
adb pull /system/lib/libsurfaceflinger.so ../../../vendor/motorola/$DEVICE/proprietary
adb pull /system/lib/libsurfaceflinger_client.so ../../../vendor/motorola/$DEVICE/proprietary

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g > ../../../vendor/motorola/$DEVICE/$DEVICE-vendor-blobs.mk
# This file is generated by device/motorola/__DEVICE__/extract-files.sh

# system-etc
PRODUCT_COPY_FILES += \\
    vendor/motorola/__DEVICE__/proprietary/01_Vendor_ti_omx.cfg:/system/etc/01_Vendor_ti_omx.cfg \\

#system-lib
PRODUCT_COPY_FILES += \\
    vendor/motorola/__DEVICE__/proprietary/libEGL_POWERVR_SGX540_120.so:obj/system/lib/egl/libEGL_POWERVR_SGX540_120.so \\
    vendor/motorola/__DEVICE__/proprietary/libGLES_android.so:obj/system/lib/egl/libGLES_android.so \\
    vendor/motorola/__DEVICE__/proprietary/libGLESv1_CM_POWERVR_SGX540_120.so:obj/system/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so \\
    vendor/motorola/__DEVICE__/proprietary/libGLESv2_POWERVR_SGX540_120.so:obj/system/lib/egl/libGLESv2_POWERVR_SGX540_120.so \\
    vendor/motorola/__DEVICE__/proprietary/libeglinfo.so:obj/system/lib/egl/libeglinfo.so \\
    vendor/motorola/__DEVICE__/proprietary/libgles1_texture_stream.so:obj/system/lib/egl/libgles1_texture_stream.so \\
    vendor/motorola/__DEVICE__/proprietary/libgles2_texture_stream.so:obj/system/lib/egl/libgles2_texture_stream.so \\

# system-lib
PRODUCT_COPY_FILES += \\
    vendor/motorola/__DEVICE__/proprietary/libEGL.so:/system/lib/egl/libEGL.so \\
    vendor/motorola/__DEVICE__/proprietary/libGLESv1_CM.so:/system/lib/egl/libGLESv1_CM.so \\
    vendor/motorola/__DEVICE__/proprietary/libGLESv2.so:/system/lib/libGLESv2.so \\
    vendor/motorola/__DEVICE__/proprietary/libIMGegl.so:/system/lib/libIMGegl.so \\
    vendor/motorola/__DEVICE__/proprietary/libVendor_ti_omx.so:/system/lib/libVendor_ti_omx.so \\
    vendor/motorola/__DEVICE__/proprietary/libVendor_ti_omx_config_parser.so:/system/lib/libVendor_ti_omx_config_parser.so \\
    vendor/motorola/__DEVICE__/proprietary/libpixelflinger.so:/system/lib/libpixelflinger.so \\
    vendor/motorola/__DEVICE__/proprietary/libsurfaceflinger.so:/system/lib/libsurfaceflinger.so \\
    vendor/motorola/__DEVICE__/proprietary/libsurfaceflinger_client.so:/system/lib/libsurfaceflinger_client.so \\
EOF

./setup-makefiles.sh
